.PHONY:all
all:bubble_sort heap_sort insert_sort merge_sort quick_sort radix_sort select_sort shell_insert_sort
bubble_sort:bubble_sort.c
	gcc -o $@ $^
heap_sort:heap_sort.c
	gcc -o $@ $^
insert_sort:insert_sort.c
	gcc -o $@ $^
merge_sort:merge_sort.c
	gcc -o $@ $^
quick_sort:quick_sort.c
	gcc -o $@ $^
radix_sort:radix_sort.c
	gcc -o $@ $^
select_sort:select_sort.c
	gcc -o $@ $^
shell_insert_sort:shell_insert_sort.c
	gcc -o $@ $^
.PHONY:clean
clean:
	rm -rf bubble_sort heap_sort insert_sort merge_sort quick_sort radix_sort select_sort shell_insert_sort
